app = "ZanesBlock"

primary_region = "iad" 

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    port = 80
